// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD13ACMiKzL95pnqj6-FIk3hF-SDKQHSOU',
    appId: '1:852353724402:web:f9a82a496ac6d102e3c56b',
    messagingSenderId: '852353724402',
    projectId: 'likelion-def27',
    authDomain: 'likelion-def27.firebaseapp.com',
    storageBucket: 'likelion-def27.firebasestorage.app',
    measurementId: 'G-MYEF4XCSF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-twRPuDiUyFDRT1qrD5dgt8L48dJvCvA',
    appId: '1:852353724402:android:1cdd0321e1a57946e3c56b',
    messagingSenderId: '852353724402',
    projectId: 'likelion-def27',
    storageBucket: 'likelion-def27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARJQLo7oJ2v5XgZhxYk2tj5aZBaZq-LB0',
    appId: '1:852353724402:ios:92c9fe492db8a3e4e3c56b',
    messagingSenderId: '852353724402',
    projectId: 'likelion-def27',
    storageBucket: 'likelion-def27.firebasestorage.app',
    iosClientId: '852353724402-k33co5aqgln64oik4vdskf6p7cqvncgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.likelion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARJQLo7oJ2v5XgZhxYk2tj5aZBaZq-LB0',
    appId: '1:852353724402:ios:92c9fe492db8a3e4e3c56b',
    messagingSenderId: '852353724402',
    projectId: 'likelion-def27',
    storageBucket: 'likelion-def27.firebasestorage.app',
    iosClientId: '852353724402-k33co5aqgln64oik4vdskf6p7cqvncgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.likelion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD13ACMiKzL95pnqj6-FIk3hF-SDKQHSOU',
    appId: '1:852353724402:web:4afb05e4ed7adcf0e3c56b',
    messagingSenderId: '852353724402',
    projectId: 'likelion-def27',
    authDomain: 'likelion-def27.firebaseapp.com',
    storageBucket: 'likelion-def27.firebasestorage.app',
    measurementId: 'G-D7F4QK97VF',
  );

}